language: node_js
node_js:
  - node
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "${TRAVIS_BUILD_DIR}/dist/docs"
  repo: Semantic-UI-Vue/semantic-ui-vue.github.io
  on:
    branch: master
